# Generated by Django 2.2.16 on 2021-08-18 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0005_auto_20210818_1127"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_title_author",
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("title", "author")},
        ),
    ]
