# Generated by Django 2.2.16 on 2021-08-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_auto_20210818_1307"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_title_author"
            ),
        ),
    ]
