# Generated by Django 2.2.16 on 2021-08-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_auto_20210818_1310"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
